# digest.py
"""
Kontext Digest Processor — extract memory-worthy facts from conversation digests.

Reads digest files generated by the Backup System, extracts user messages
and key exchanges, produces a list of candidate facts for review or
auto-import into the Kontext database.

The processor works in two modes:
  1. Extract mode (default) — pulls candidate facts from digests, writes
     them to _digest_candidates.md for review
  2. Auto mode — imports high-confidence facts directly into the database

Usage:
    python digest.py                    # Extract candidates from pending digests
    python digest.py --auto             # Auto-import high-confidence facts
    python digest.py --dry-run          # Show what would be extracted
    python digest.py --file <path>      # Process a specific digest file
"""

import re
import sys
import logging
import argparse
from pathlib import Path
from datetime import datetime, timezone

from db import KontextDB

__version__ = "1.0"

LOG = Path(__file__).parent / "_digest.log"
def _find_digest_dir() -> Path:
    """Auto-detect digest directory. Checks common locations."""
    candidates = [
        Path.home() / "Desktop" / "Claude" / "Backup System" / "_digests",
        Path.home() / "Documents" / "Claude" / "Backup System" / "_digests",
        Path(__file__).parent.parent / "Backup System" / "_digests",
    ]
    for d in candidates:
        if d.exists():
            return d
    return candidates[0]  # Default to first candidate

DIGEST_DIR = _find_digest_dir()
MANIFEST = DIGEST_DIR / "_manifest.md"
PENDING_FLAG = DIGEST_DIR.parent / "_digest-pending"
CANDIDATES_FILE = Path(__file__).parent / "_digest_candidates.md"

import logging.handlers
_log = logging.getLogger("kontext.digest")
if not _log.handlers:
    _log.setLevel(logging.INFO)
    _h = logging.handlers.RotatingFileHandler(
        str(LOG), maxBytes=1_000_000, backupCount=2, encoding="utf-8"
    )
    _h.setFormatter(logging.Formatter("%(asctime)s %(levelname)s %(message)s"))
    _log.addHandler(_h)

# ---------------------------------------------------------------------------
# Haiku distillation — turns raw user messages into clean third-person facts
# ---------------------------------------------------------------------------

HAIKU_MODEL = "claude-haiku-4-5-20251001"

_DISTILL_PROMPT = (
    "Rewrite the raw chat message below as a single-line third-person memory fact "
    "for a personal knowledge base owned by a user named Ionut.\n\n"
    "Rules:\n"
    "- Output ONE line under 120 characters.\n"
    "- Third person ('Ionut...', 'User...'), never first person.\n"
    "- Drop hedges, filler, conversational framing. Keep numbers, names, dates, decisions.\n"
    "- If the message contains no durable fact (just chatter), output exactly: SKIP\n"
    "- No quotes, no markdown, no preamble. Just the fact, or SKIP.\n\n"
    "Message:\n{text}"
)

_distill_unavailable = False  # set after first failure to avoid retry storms


def distill_with_haiku(text: str) -> str | None:
    """Rewrite a raw user message as a clean third-person fact via Claude Haiku.

    Shells out to the `claude` CLI (one-shot mode) so we reuse Claude Code's
    existing auth — no API key plumbing required. Returns the distilled fact,
    or None if:
      - The `claude` CLI is missing or fails to launch
      - Haiku judges the message has no durable content (returns 'SKIP')
      - The subprocess errors / times out

    Caller MUST handle None — do not fall back to the raw message, since the
    whole point of distillation is to keep raw chatter out of memory.
    """
    global _distill_unavailable
    if _distill_unavailable:
        return None
    import subprocess, shutil, os, tempfile, json as _json
    from pathlib import Path as _Path
    cli = shutil.which("claude")
    if not cli:
        _log.warning("DISTILL: `claude` CLI not on PATH — distillation disabled for this run")
        _distill_unavailable = True
        return None
    # Batch-mode hardening. The env var alone is insufficient: even if the
    # hooks skip, `claude --print` still cold-boots every MCP server in the
    # user-scope settings.json (Serena LSP init alone is 10-30s). With
    # parallel workers that's a certain deadlock. The fix is an empty
    # --mcp-config file plus --strict-mcp-config, which tells Claude Code
    # to load ZERO MCP servers for this subprocess.
    empty_mcp = _Path(tempfile.gettempdir()) / "kontext-empty-mcp.json"
    if not empty_mcp.exists():
        empty_mcp.write_text(_json.dumps({"mcpServers": {}}), encoding="utf-8")
    env = os.environ.copy()
    env["KONTEXT_SKIP_HOOKS"] = "1"  # belt + suspenders with --strict-mcp-config
    scratch_cwd = tempfile.gettempdir()
    try:
        proc = subprocess.run(
            [
                cli, "-p", _DISTILL_PROMPT.format(text=text),
                "--model", HAIKU_MODEL,
                "--strict-mcp-config",
                "--mcp-config", str(empty_mcp),
            ],
            capture_output=True, text=True, timeout=45,
            encoding="utf-8", errors="replace",
            env=env, cwd=scratch_cwd,
        )
    except (subprocess.TimeoutExpired, OSError) as e:
        _log.warning(f"DISTILL: subprocess failed — {e}")
        return None
    if proc.returncode != 0:
        _log.warning(f"DISTILL: claude CLI rc={proc.returncode} stderr={proc.stderr[:200]}")
        return None
    out = (proc.stdout or "").strip()
    if not out or out.upper() == "SKIP":
        return None
    # Safety: enforce single line + length cap even if model misbehaves
    out = out.splitlines()[0].strip().strip('"').strip("'")
    if out.upper() == "SKIP" or not out:
        return None
    if len(out) > 200:
        out = out[:197] + "..."
    return out


# ---------------------------------------------------------------------------
# Patterns that signal memory-worthy content in user messages
# ---------------------------------------------------------------------------

_HIGH_SIGNAL_PATTERNS = [
    # Decisions (EN + RO)
    (re.compile(r"\b(I('m| am) going (with|to)|decided|choosing|switching to|killing|dropping|cancell?ing|am decis|merg pe|m-am hotărât|renunț la|vreau să)\b", re.I), "decision", 8),
    # Facts about self (EN + RO)
    (re.compile(r"\b(I have|I got|I('m| am)|my .+ is|I started|I stopped|I moved|I bought|I sold|eu sunt|am început|m-am mutat|am cumpărat|am vândut)\b", re.I), "self_fact", 6),
    # Corrections (EN + RO)
    (re.compile(r"\b(actually|no,? it'?s|correction|not \d+,? (it'?s|but) \d+|wrong|update that|de fapt|nu e așa|am greșit|corecție)\b", re.I), "correction", 9),
    # Status changes (EN + RO)
    (re.compile(r"\b(is live|launched|shipped|deployed|stalled|paused|cancelled|finished|completed|am lansat|am livrat|s-a blocat|am terminat|am anulat|e live)\b", re.I), "status_change", 8),
    # Financial (EN + RO)
    (re.compile(r"\b(\$\d+|€\d+|\d+ ?(RON|EUR|USD|lei)|revenue|income|tax|invoice|PFA|ANAF|venit|factură|impozit|plată|taxe)\b", re.I), "financial", 7),
    # Preferences / feedback (EN + RO)
    (re.compile(r"\b(don'?t|stop|never|always|I (like|prefer|want|hate|need)|from now on|prefer|urăsc|îmi place|nu vreau|am nevoie|de acum)\b", re.I), "preference", 7),
    # People (EN + RO)
    (re.compile(r"\b(Luiza|mama|mother|student|client|friend|elev|elevă|prieten|prietenă)\b", re.I), "people", 6),
    # Goals / plans (EN + RO)
    (re.compile(r"\b(goal|plan|target|deadline|by (January|February|March|April|May|June|July|August|September|October|November|December)|obiectiv|termen|până în (ianuarie|februarie|martie|aprilie|mai|iunie|iulie|august|septembrie|octombrie|noiembrie|decembrie))\b", re.I), "goal", 7),
    # Numbers that matter (EN + RO)
    (re.compile(r"\b\d{2,}\s*(students?|reviews?|subscribers?|followers?|clients?|lessons?|sessions?|elevi|recenzii|abonați|clienți|lecții|ședințe)\b", re.I), "metric", 8),
]

# Patterns that indicate noise (skip these messages)
_NOISE_PATTERNS = [
    re.compile(r"^\s*(ok|yes|no|sure|thanks|thank you|got it|cool|nice|perfect|good|great|fine|hmm|hm)\s*[.!]?\s*$", re.I),
    re.compile(r"^\s*(hello|hi|hey|yo)\s*[.!]?\s*$", re.I),
    # Romanian noise
    re.compile(r"^\s*(da|nu|bine|ok|mersi|mulțumesc|super|perfect|gata|sigur)\s*[.!]?\s*$", re.I),
    re.compile(r"^\s*(salut|bună|hei|neața)\s*[.!]?\s*$", re.I),
    re.compile(r"^\[Tool:", re.I),  # Tool use markers in digests
    re.compile(r"^#+\s*\[", re.I),  # Timestamp headers
    re.compile(r"Base directory for this skill:", re.I),  # Skill system messages
    re.compile(r"<system-reminder>", re.I),  # System reminders
    re.compile(r"^```", re.I),  # Code blocks
    re.compile(r"^\s*\{", re.I),  # JSON fragments
]


# ---------------------------------------------------------------------------
# Digest parsing
# ---------------------------------------------------------------------------

def parse_digest(filepath: Path) -> list[dict]:
    """Parse a digest markdown file into a list of messages.

    Returns list of {role, text, timestamp, session} dicts.
    Only keeps USER messages (Claude responses are context, not memory).
    """
    content = filepath.read_text(encoding="utf-8", errors="replace")
    messages = []
    current_session = 0
    current_role = None
    current_text_lines = []
    current_timestamp = ""

    session_re = re.compile(r"^## Session (\d+)")
    msg_re = re.compile(r"^### \[(\d{2}:\d{2})\] \*\*(\w+)\*\*")

    for line in content.split("\n"):
        session_match = session_re.match(line)
        if session_match:
            # Flush previous message
            if current_role == "USER" and current_text_lines:
                text = "\n".join(current_text_lines).strip()
                if text and len(text) > 10:
                    messages.append({
                        "role": "USER",
                        "text": text,
                        "timestamp": current_timestamp,
                        "session": current_session,
                    })
            current_session = int(session_match.group(1))
            current_role = None
            current_text_lines = []
            continue

        msg_match = msg_re.match(line)
        if msg_match:
            # Flush previous message
            if current_role == "USER" and current_text_lines:
                text = "\n".join(current_text_lines).strip()
                if text and len(text) > 10:
                    messages.append({
                        "role": "USER",
                        "text": text,
                        "timestamp": current_timestamp,
                        "session": current_session,
                    })
            current_timestamp = msg_match.group(1)
            current_role = msg_match.group(2)
            current_text_lines = []
            continue

        if current_role == "USER":
            current_text_lines.append(line)

    # Flush last message
    if current_role == "USER" and current_text_lines:
        text = "\n".join(current_text_lines).strip()
        if text and len(text) > 10:
            messages.append({
                "role": "USER",
                "text": text,
                "timestamp": current_timestamp,
                "session": current_session,
            })

    return messages


def is_noise(text: str) -> bool:
    """Check if a message is noise (greetings, acknowledgments, tool markers)."""
    for pattern in _NOISE_PATTERNS:
        if pattern.match(text):
            return True
    return False


def score_message(text: str) -> list[dict]:
    """Score a user message for memory-worthiness.

    Returns list of {pattern_type, grade, match} for all matching patterns.
    """
    hits = []
    for pattern, ptype, grade in _HIGH_SIGNAL_PATTERNS:
        match = pattern.search(text)
        if match:
            hits.append({
                "type": ptype,
                "grade": grade,
                "match": match.group(0),
            })
    return hits


# ---------------------------------------------------------------------------
# Candidate extraction
# ---------------------------------------------------------------------------

def extract_candidates(filepath: Path) -> list[dict]:
    """Extract memory-worthy candidates from a single digest file.

    Returns list of {text, grade, type, source, session, timestamp} dicts.
    """
    messages = parse_digest(filepath)
    candidates = []

    project_name = filepath.stem.replace("-", " ").title()
    today = datetime.now(timezone.utc).strftime("%Y-%m")

    for msg in messages:
        text = msg["text"]
        if is_noise(text):
            continue

        # Skip very short messages (low information density)
        if len(text) < 30:
            continue

        # Skip very long messages (likely code or system dumps, not facts)
        if len(text) > 1000:
            continue

        hits = score_message(text)
        if not hits:
            continue

        # Require either a high-grade hit (8+) or multiple pattern matches
        best = max(hits, key=lambda h: h["grade"])
        if best["grade"] < 8 and len(hits) < 2:
            continue

        # Truncate for storage
        if len(text) > 300:
            text = text[:297] + "..."

        candidates.append({
            "text": text,
            "grade": best["grade"],
            "type": best["type"],
            "source": f"[digest {today}]",
            "session": msg["session"],
            "timestamp": msg["timestamp"],
            "project": project_name,
        })

    return candidates


def deduplicate_candidates(candidates: list[dict], db: KontextDB) -> list[dict]:
    """Remove candidates that already exist in the database (85% similarity threshold)."""
    from difflib import SequenceMatcher

    # Load all DB facts once for efficient comparison
    all_entries = db.conn.execute("SELECT fact FROM entries").fetchall()
    db_facts = [row[0].lower() for row in all_entries]

    fresh = []
    for c in candidates:
        text_lower = c["text"].lower()
        is_dup = any(
            SequenceMatcher(None, text_lower, f).ratio() >= 0.85
            for f in db_facts
        )
        if not is_dup:
            fresh.append(c)
    return fresh


# ---------------------------------------------------------------------------
# File routing — map digest projects to memory files
# ---------------------------------------------------------------------------

_PROJECT_TO_FILE = {
    "finance": "user_financial_architecture.md",
    "pfa": "user_financial_architecture.md",
    "contabilitate": "user_financial_architecture.md",
    "skool": "project_vocality_content.md",
    "youtube": "project_vocality_content.md",
    "personal context": "user_identity.md",
    "kontext": "design_principles.md",
    "tool auditor": "tool_registry.md",
}


def route_to_file(project_name: str, candidate_type: str) -> str:
    """Determine which memory file a candidate belongs to."""
    name_lower = project_name.lower()
    for keyword, filename in _PROJECT_TO_FILE.items():
        if keyword in name_lower:
            return filename

    # Route by type if project doesn't match
    type_routes = {
        "financial": "user_financial_architecture.md",
        "preference": "feedback_ai_interaction.md",
        "correction": "feedback_ai_interaction.md",
        "people": "user_identity.md",
        "self_fact": "user_identity.md",
        "goal": "project_goals.md",
        "decision": "project_goals.md",
        "metric": "project_goals.md",
        "status_change": "project_goals.md",
    }
    return type_routes.get(candidate_type, "user_identity.md")


# ---------------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------------

def write_candidates_file(candidates: list[dict], output_path: Path):
    """Write candidates to a markdown file for LLM distillation and review.

    Format is designed for the /kontext process-digest subagents to read,
    distill raw messages into atomic facts, and import via kontext_write.
    """
    lines = [
        "# Digest Candidates — Awaiting Distillation",
        f"**Generated:** {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M')} UTC",
        f"**Candidates:** {len(candidates)}",
        "",
        "These are raw user messages extracted by pattern matching.",
        "They need LLM distillation before import — convert each into atomic facts.",
        "",
        "**Distillation rules:**",
        "- Convert raw message → 1-3 atomic facts (single statement per fact)",
        "- Strip conversational filler, keep only the fact itself",
        '- Example: "I have 42 active students right now, up from 38" →',
        "  - `Active students: 42 (up from 38)` [grade 9, self_fact]",
        "- Include dated source tag from the digest session date",
        "- Grade 8-10 for decisions/identity/metrics, 5-7 for soft context",
        "",
        "Run `/kontext process-digest` to trigger LLM distillation and import.",
        "",
    ]

    by_project = {}
    for c in candidates:
        by_project.setdefault(c["project"], []).append(c)

    for project, items in sorted(by_project.items()):
        lines.append(f"## {project}")
        lines.append("")
        for c in items:
            lines.append(f"- **[{c['type']}, g{c['grade']}]** {c['text']}")
            lines.append(f"  → target: `{route_to_file(c['project'], c['type'])}` | source: `{c.get('source', 'unknown')}`")
        lines.append("")

    output_path.write_text("\n".join(lines), encoding="utf-8")


def auto_import(candidates: list[dict], db: KontextDB, min_grade: int = 7,
                distill: bool = True) -> dict:
    """Auto-import high-confidence candidates into the database.

    Each candidate above min_grade is sent through Haiku distillation
    (`distill_with_haiku`) to convert raw first-person chat into a clean
    third-person memory fact before storage. Candidates that Haiku marks SKIP
    or that fail distillation are dropped — we never store raw chatter.

    Set distill=False to skip the LLM pass (used by tests).

    Returns {imported, skipped, distill_dropped, conflicts_found, total}.
    """
    imported = 0
    skipped = 0
    distill_dropped = 0

    for c in candidates:
        if c["grade"] < min_grade:
            skipped += 1
            continue

        if distill:
            clean = distill_with_haiku(c["text"])
            if clean is None:
                distill_dropped += 1
                _log.info(f"DISTILL_SKIP: g{c['grade']} {c['text'][:60]}")
                continue
            fact_text = clean
        else:
            fact_text = c["text"]

        target_file = route_to_file(c["project"], c["type"])
        db.add_entry(
            file=target_file,
            fact=fact_text,
            source=c["source"],
            grade=c["grade"],
            tier="active",
        )
        imported += 1
        _log.info(f"IMPORT: [{target_file}] g{c['grade']} {fact_text[:60]}")

    # Run conflict detection after import to catch contradictions
    conflicts_found = 0
    if imported > 0:
        new_conflicts = db.detect_conflicts()
        conflicts_found = len(new_conflicts)
        if conflicts_found > 0:
            _log.warning(f"IMPORT: {conflicts_found} new conflict(s) detected after import")

    return {"imported": imported, "skipped": skipped, "distill_dropped": distill_dropped,
            "conflicts_found": conflicts_found, "total": len(candidates)}


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def process_digests(auto: bool = False, dry_run: bool = False,
                    specific_file: Path = None, min_grade: int = 7) -> dict:
    """Process all pending digests or a specific file.

    Returns {files_processed, candidates_found, candidates_fresh, imported}.
    """
    db = KontextDB()
    results = {
        "files_processed": 0,
        "candidates_found": 0,
        "candidates_fresh": 0,
        "imported": 0,
    }

    if specific_file:
        files = [specific_file]
    else:
        if not MANIFEST.exists():
            _log.warning("No manifest found — run update-memory.sh first")
            print("No digest manifest found. Run the backup system first.")
            db.close()
            return results
        # Parse manifest to get file list
        files = list(DIGEST_DIR.glob("*.md"))
        files = [f for f in files if f.name != "_manifest.md"]

    all_candidates = []
    successfully_processed: list[Path] = []  # for move-to-_processed below
    for filepath in files:
        if not filepath.exists():
            _log.warning(f"Digest file missing: {filepath}")
            continue

        candidates = extract_candidates(filepath)
        results["files_processed"] += 1
        results["candidates_found"] += len(candidates)
        all_candidates.extend(candidates)
        successfully_processed.append(filepath)
        _log.info(f"EXTRACT: {filepath.name} → {len(candidates)} candidates")

    # Deduplicate across digest files (same message can appear in overlapping digests).
    # Two-pass: cheap 80-char prefix exact-match, then fuzzy 0.85 similarity over
    # what survives — catches "Active students: 24" vs "Active students: 24 paying"
    # the same way sync.py already does for flat-file imports.
    from difflib import SequenceMatcher
    seen_prefixes = set()
    unique_candidates = []
    for c in all_candidates:
        key = c["text"][:80]
        if key in seen_prefixes:
            continue
        # Fuzzy check against already-kept candidates
        is_dup = False
        c_lower = c["text"].lower()
        for kept in unique_candidates:
            if SequenceMatcher(None, c_lower, kept["text"].lower()).ratio() >= 0.85:
                is_dup = True
                break
        if is_dup:
            continue
        seen_prefixes.add(key)
        unique_candidates.append(c)

    # Deduplicate against existing database
    fresh = deduplicate_candidates(unique_candidates, db)
    results["candidates_fresh"] = len(fresh)

    if dry_run:
        print(f"Would process {len(fresh)} fresh candidates from {results['files_processed']} files")
        for c in fresh[:20]:
            print(f"  [{c['type']}, g{c['grade']}] {c['text'][:80]}")
        db.close()
        return results

    if auto:
        import_results = auto_import(fresh, db, min_grade=min_grade)
        results["imported"] = import_results["imported"]
        _log.info(f"AUTO-IMPORT: {import_results}")

        # Re-export affected files
        if import_results["imported"] > 0:
            from export import export_all, export_memory_index
            from mcp_server import find_memory_dir
            mem_dir = find_memory_dir()
            if mem_dir:
                export_all(db, mem_dir)
                export_memory_index(db, mem_dir)
    else:
        # Write candidates file for manual review
        write_candidates_file(fresh, CANDIDATES_FILE)
        print(f"Wrote {len(fresh)} candidates to {CANDIDATES_FILE}")

    # Move successfully processed files to _processed/ so the next run doesn't
    # re-parse them. DB-level dedup makes re-parsing safe but wasteful, and
    # orphans in _digests/ now clearly mean "unfinished work" — useful signal
    # for partial-crash recovery.
    if not specific_file and successfully_processed:
        processed_dir = DIGEST_DIR / "_processed"
        try:
            processed_dir.mkdir(exist_ok=True)
            for fp in successfully_processed:
                target = processed_dir / fp.name
                if target.exists():
                    target.unlink()  # idempotent re-runs
                fp.rename(target)
            _log.info(f"ARCHIVED: {len(successfully_processed)} files → {processed_dir}")
        except OSError as e:
            _log.warning(f"ARCHIVE: failed to move processed files — {e}")

    # Clear the pending flag
    if PENDING_FLAG.exists() and not specific_file:
        PENDING_FLAG.unlink()
        _log.info("Cleared _digest-pending flag")

    db.close()
    return results


def main() -> int:
    parser = argparse.ArgumentParser(description="Kontext Digest Processor")
    parser.add_argument("--auto", action="store_true", help="Auto-import high-confidence facts (grade >= 7)")
    parser.add_argument("--dry-run", action="store_true", help="Show what would be extracted")
    parser.add_argument("--file", type=str, help="Process a specific digest file")
    parser.add_argument("--min-grade", type=int, default=7, help="Minimum grade for auto-import (default 7)")
    args = parser.parse_args()

    specific = Path(args.file) if args.file else None
    results = process_digests(
        auto=args.auto,
        dry_run=args.dry_run,
        specific_file=specific,
        min_grade=args.min_grade,
    )

    print(f"\nDigest processing complete:")
    print(f"  Files processed:  {results['files_processed']}")
    print(f"  Candidates found: {results['candidates_found']}")
    print(f"  Fresh (new):      {results['candidates_fresh']}")
    print(f"  Imported:         {results['imported']}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
